name: authentication
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0  # Adicione a versão da biblioteca intl
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1   # Verifique a versão mais recente que é compatível
  google_sign_in: ^6.2.1
  firebase_core: ^3.6.0    # Mantenha esta versão para compatibilidade
  cloud_firestore: ^5.4.4 
  get: ^4.6.6
  http: ^1.2.2
  fl_chart: ^0.69.2
  flutter_multi_formatter: ^2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
 

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true